In [62]:
import pandas as pd

In [63]:
df = pd.read_csv('Amazon Sales data.csv')

In [64]:
df.head(10)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,5/28/2010,669165933,6/27/2010,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,8/22/2012,963881480,9/15/2012,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,05-02-2014,341417157,05-08-2014,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,6/20/2014,514321792,07-05-2014,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,02-01-2013,115456712,02-06-2013,5062,651.21,524.96,3296425.02,2657347.52,639077.50
5,Australia and Oceania,Solomon Islands,Baby Food,Online,C,02-04-2015,547995746,2/21/2015,2974,255.28,159.42,759202.72,474115.08,285087.64
6,Sub-Saharan Africa,Angola,Household,Offline,M,4/23/2011,135425221,4/27/2011,4187,668.27,502.54,2798046.49,2104134.98,693911.51
7,Sub-Saharan Africa,Burkina Faso,Vegetables,Online,H,7/17/2012,871543967,7/27/2012,8082,154.06,90.93,1245112.92,734896.26,510216.66
8,Sub-Saharan Africa,Republic of the Congo,Personal Care,Offline,M,7/14/2015,770463311,8/25/2015,6070,81.73,56.67,496101.10,343986.90,152114.20
9,Sub-Saharan Africa,Senegal,Cereal,Online,H,4/18/2014,616607081,5/30/2014,6593,205.70,117.11,1356180.10,772106.23,584073.87

In [65]:
df.dtypes

Region             object
Country            object
Item Type          object
Sales Channel      object
Order Priority     object
Order Date         object
Order ID            int64
Ship Date          object
Units Sold          int64
Unit Price        float64
Unit Cost         float64
Total Revenue     float64
Total Cost        float64
Total Profit      float64
dtype: object

In [66]:
df = df.astype({'Ship Date': 'datetime64[ns]','Order Date':'datetime64[ns]'})

In [67]:
df.dtypes

Region                    object
Country                   object
Item Type                 object
Sales Channel             object
Order Priority            object
Order Date        datetime64[ns]
Order ID                   int64
Ship Date         datetime64[ns]
Units Sold                 int64
Unit Price               float64
Unit Cost                float64
Total Revenue            float64
Total Cost               float64
Total Profit             float64
dtype: object

In [68]:
df.head(20)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Australia and Oceania,Tuvalu,Baby Food,Offline,H,2010-05-28,669165933,2010-06-27,9925,255.28,159.42,2533654.00,1582243.50,951410.50
1,Central America and the Caribbean,Grenada,Cereal,Online,C,2012-08-22,963881480,2012-09-15,2804,205.70,117.11,576782.80,328376.44,248406.36
2,Europe,Russia,Office Supplies,Offline,L,2014-05-02,341417157,2014-05-08,1779,651.21,524.96,1158502.59,933903.84,224598.75
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Online,C,2014-06-20,514321792,2014-07-05,8102,9.33,6.92,75591.66,56065.84,19525.82
4,Sub-Saharan Africa,Rwanda,Office Supplies,Offline,L,2013-02-01,115456712,2013-02-06,5062,651.21,524.96,3296425.02,2657347.52,639077.50
5,Australia and Oceania,Solomon Islands,Baby Food,Online,C,2015-02-04,547995746,2015-02-21,2974,255.28,159.42,759202.72,474115.08,285087.64
6,Sub-Saharan Africa,Angola,Household,Offline,M,2011-04-23,135425221,2011-04-27,4187,668.27,502.54,2798046.49,2104134.98,693911.51
7,Sub-Saharan Africa,Burkina Faso,Vegetables,Online,H,2012-07-17,871543967,2012-07-27,8082,154.06,90.93,1245112.92,734896.26,510216.66
8,Sub-Saharan Africa,Republic of the Congo,Personal Care,Offline,M,2015-07-14,770463311,2015-08-25,6070,81.73,56.67,496101.10,343986.90,152114.20
9,Sub-Saharan Africa,Senegal,Cereal,Online,H,2014-04-18,616607081,2014-05-30,6593,205.70,117.11,1356180.10,772106.23,584073.87
10,Asia,Kyrgyzstan,Vegetables,Online,H,2011-06-24,814711606,2011-07-12,124,154.06,90.93,19103.44,11275.32,7828.12
11,Sub-Saharan Africa,Cape Verde,Clothes,Offline,H,2014-08-02,939825713,2014-08-19,4168,109.28,35.84,455479.04,149381.12,306097.92
12,Asia,Bangladesh,Clothes,Online,L,2017-01-13,187310731,2017-03-01,8263,109.28,35.84,902980.64,296145.92,606834.72
13,Central America and the Caribbean,Honduras,Household,Offline,H,2017-02-08,522840487,2017-02-13,8974,668.27,502.54,5997054.98,4509793.96,1487261.02
14,Asia,Mongolia,Personal Care,Offline,C,2014-02-19,832401311,2014-02-23,4901,81.73,56.67,400558.73,277739.67,122819.06
15,Europe,Bulgaria,Clothes,Online,M,2012-04-23,972292029,2012-06-03,1673,109.28,35.84,182825.44,59960.32,122865.12
16,Asia,Sri Lanka,Cosmetics,Offline,M,2016-11-19,419123971,2016-12-18,6952,437.20,263.33,3039414.40,1830670.16,1208744.24
17,Sub-Saharan Africa,Cameroon,Beverages,Offline,C,2015-04-01,519820964,2015-04-18,5430,47.45,31.79,257653.50,172619.70,85033.80
18,Asia,Turkmenistan,Household,Offline,L,2010-12-30,441619336,2011-01-20,3830,668.27,502.54,2559474.10,1924728.20,634745.90
19,Australia and Oceania,East Timor,Meat,Online,L,2012-07-31,322067916,2012-09-11,5908,421.89,364.69,2492526.12,2154588.52,337937.60

In [69]:
df.describe()

,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,100,1.000000e+02,100,100.000000,100.000000,100.000000,1.000000e+02,1.000000e+02,1.000000e+02
mean,2013-09-16 14:09:36,5.550204e+08,2013-10-09 22:48:00,5128.710000,276.761300,191.048000,1.373488e+06,9.318057e+05,4.416820e+05
min,2010-02-02 00:00:00,1.146066e+08,2010-02-25 00:00:00,124.000000,9.330000,6.920000,4.870260e+03,3.612240e+03,1.258020e+03
25%,2012-02-14 12:00:00,3.389225e+08,2012-02-24 18:00:00,2836.250000,81.730000,35.840000,2.687212e+05,1.688680e+05,1.214436e+05
50%,2013-07-12 12:00:00,5.577086e+08,2013-08-11 12:00:00,5382.500000,179.880000,107.275000,7.523144e+05,3.635664e+05,2.907680e+05
75%,2015-04-07 00:00:00,7.907551e+08,2015-04-28 00:00:00,7369.000000,437.200000,263.330000,2.212045e+06,1.613870e+06,6.358288e+05
max,2017-05-22 00:00:00,9.940222e+08,2017-06-17 00:00:00,9925.000000,668.270000,524.960000,5.997055e+06,4.509794e+06,1.719922e+06
std,NaN,2.606153e+08,NaN,2794.484562,235.592241,188.208181,1.460029e+06,1.083938e+06,4.385379e+05

In [70]:
df.isnull().sum()

Region            0
Country           0
Item Type         0
Sales Channel     0
Order Priority    0
Order Date        0
Order ID          0
Ship Date         0
Units Sold        0
Unit Price        0
Unit Cost         0
Total Revenue     0
Total Cost        0
Total Profit      0
dtype: int64

In [71]:
df.duplicated().sum()

np.int64(0)

In [72]:
df[df.duplicated()]

Empty DataFrame
Columns: [Region, Country, Item Type, Sales Channel, Order Priority, Order Date, Order ID, Ship Date, Units Sold, Unit Price, Unit Cost, Total Revenue, Total Cost, Total Profit]
Index: []

In [73]:
df['Shipping_Days'] = (df['Ship Date'] - df['Order Date']).dt.days

In [74]:
df['Profit_Margin_%'] = (df['Total Profit'] / df['Total Revenue']) * 100

In [75]:
df['shipping_category'] = pd.cut(df['Shipping_Days'], bins=[-1, 5, 10, 20, float('inf')], labels=['Super Fast','Fast','Slow','Delayed'])

In [76]:
df.columns

Index(['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority',
       'Order Date', 'Order ID', 'Ship Date', 'Units Sold', 'Unit Price',
       'Unit Cost', 'Total Revenue', 'Total Cost', 'Total Profit',
       'Shipping_Days', 'Profit_Margin_%', 'shipping_category'],
      dtype='object')

In [77]:
df['Profit Categoty'] = pd.qcut(df['Total Profit'], q=3, labels=['Low', 'Medium', 'High'])

In [78]:
df.columns.str.lower().str.replace(' ', '_')

Index(['region', 'country', 'item_type', 'sales_channel', 'order_priority',
       'order_date', 'order_id', 'ship_date', 'units_sold', 'unit_price',
       'unit_cost', 'total_revenue', 'total_cost', 'total_profit',
       'shipping_days', 'profit_margin_%', 'shipping_category',
       'profit_categoty'],
      dtype='object')

In [79]:
# Are there any negative shipping days?
df[df['Shipping_Days'] < 0]

Empty DataFrame
Columns: [Region, Country, Item Type, Sales Channel, Order Priority, Order Date, Order ID, Ship Date, Units Sold, Unit Price, Unit Cost, Total Revenue, Total Cost, Total Profit, Shipping_Days, Profit_Margin_%, shipping_category, Profit Categoty]
Index: []

In [80]:
pip install sqlalchemy pyodbc

Requirement already satisfied: sqlalchemy in c:\users\chakra vardhan reddy\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pyodbc in c:\users\chakra vardhan reddy\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: greenlet>=1 in c:\users\chakra vardhan reddy\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\chakra vardhan reddy\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [81]:
from sqlalchemy import create_engine

server = r'localhost\SQLEXPRESS'
database = 'Amazon_Sales'   

connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes"
)

engine = create_engine(connection_string)

print("Connected successfully")

Connected successfully

In [82]:
# Upload dataframe as SQL table
df.to_sql(
    name='amazon_sales',
    con=engine,
    if_exists='replace',
    index=False
)

print("Amazon sales data uploaded to SQL Server successfully.")

Amazon sales data uploaded to SQL Server successfully.